// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXhMxXZoXTl1kqxHoPVHY10P4GPNCWnW8',
    appId: '1:113484449349:web:10c793a838cd7a88aec52c',
    messagingSenderId: '113484449349',
    projectId: 'quiz-app-mohib',
    authDomain: 'quiz-app-mohib.firebaseapp.com',
    storageBucket: 'quiz-app-mohib.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmFQEfqgvtmkyxxqJdDe11QRloXIpeu5w',
    appId: '1:113484449349:android:ec24f09d8f4fe756aec52c',
    messagingSenderId: '113484449349',
    projectId: 'quiz-app-mohib',
    storageBucket: 'quiz-app-mohib.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUhZf9CitKwL1u6nYxJKM718_Af4Zd8Ms',
    appId: '1:113484449349:ios:70153e98f0a52d44aec52c',
    messagingSenderId: '113484449349',
    projectId: 'quiz-app-mohib',
    storageBucket: 'quiz-app-mohib.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUhZf9CitKwL1u6nYxJKM718_Af4Zd8Ms',
    appId: '1:113484449349:ios:70153e98f0a52d44aec52c',
    messagingSenderId: '113484449349',
    projectId: 'quiz-app-mohib',
    storageBucket: 'quiz-app-mohib.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXhMxXZoXTl1kqxHoPVHY10P4GPNCWnW8',
    appId: '1:113484449349:web:287c6b7b7b5835ecaec52c',
    messagingSenderId: '113484449349',
    projectId: 'quiz-app-mohib',
    authDomain: 'quiz-app-mohib.firebaseapp.com',
    storageBucket: 'quiz-app-mohib.firebasestorage.app',
  );
}
